version: '3.9'
services:
  backend:
    container_name: api
    build: .
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: dev 
    volumes: 
      - ./src:/app-backend/src
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - APP_PORT=${APP_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 60s
      retries: 15
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    cap_add:
      - SYS_NICE